import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Threads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${geistMono.variable} sm:pt-5 antialiased text-[16px]`}
      >
        <div className="sm:w-[600px] rounded-2xl min-h-dvh mx-auto sm:shadow-sm sm:shadow-bordercolor sm:bg-[#181818] p-5">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
